Repository vtenh/terraform-starter-kits, pull requests merged in 2021-01, with the labels that each got.

#18 Close #17 S3 CORS for direct upload
  locals.tf
  main.tf
  modules/s3/main.tf
  modules/s3/variables.tf
Labels: documentation, good first issue

#20 Close #19 Redirect non-www to www with alb listener rule
  main.tf
  modules/ecs_fargate/main.tf
  modules/ecs_fargate/variables.tf
Labels: good first issue

#24 close #23 app log to cloudwatch via stdout and custom command
  locals.tf
  modules/ecs_role/template/ec2_instanace_policy.json
  modules/ecs_role/template/task_policy.json
  outputs.tf
  template/container_def.json.tpl
  test/data_template_file/locals.tf
  test/data_template_file/main.tf
  test/data_template_file/outputs.tf
  test/data_template_file/template/test.json.tpl
  variables.config.tf.example
Labels: documentation, good first issue

#27 Close #25 add container insights to ecs fargate module
  modules/ecs_fargate/main.tf
  modules/ecs_fargate/variables.tf
Labels: enhancement, good first issue

#29 28 run one off task ecs
  main.tf
  modules/ecs_one_off_task/main.tf
  modules/ecs_one_off_task/variables.tf
  modules/ecs_scheduled_task/output.tf
  test/data_template_file/locals.tf
  test/json/main.tf
  variables.config.tf.example
Labels: good first issue

#35 Close #30 elasticache redis
  locals.tf
  main.tf
  modules/elasticache_redis/main.tf
  modules/elasticache_redis/outputs.tf
  modules/elasticache_redis/variables.tf
  outputs.tf
  template/container_def.json.tpl
Labels: good first issue

#34 Close #32 refactor to run sidekiq queue in existing fargate cluster
  locals.tf
  main.tf
  modules/ecs_run_task/main.tf
  modules/ecs_run_task/output.tf
  modules/ecs_run_task/template/policy.json
  modules/ecs_run_task/template/role.json
  modules/ecs_run_task/variables.tf
  template/container_def.json.tpl
  variables.config.tf.example
Labels: enhancement, good first issue

#38 Close #36 elasticache memcached for cache store
  locals.tf
  main.tf
  modules/elasticache_memcached/main.tf
  modules/elasticache_memcached/outputs.tf
  modules/elasticache_memcached/variables.tf
  outputs.tf
  template/container_def.json.tpl
Labels: good first issue
