Repository vtenh/terraform-starter-kits, pull requests merged in 2021-02, with the labels that each got.

#41 Close #39 add output command to ecs_one_off_task module
  modules/ecs_one_off_task/outputs.tf
  outputs.tf
Labels: good first issue

#44 Close #43 Sendgrid domain verification in route53 using CNAME
  main.tf
  modules/route53/main.tf
  modules/route53/variables.tf
  variables.config.tf.example
Labels: good first issue

#42 Close #40 rename HOST to DEFAULT_URL_HOST
  template/container_def.json.tpl
Labels: good first issue

#46 Close #45 Allow s3 module to have cords from local server
  locals.tf
  modules/s3/main.tf
  variables.config.tf.example
Labels: enhancement, good first issue, invalid

#51 Close #48 Add parameter key store
  locals.tf
  main.tf
  modules/ecs_role/main.tf
  template/container_def.json.tpl
Labels: good first issue

#56 Close #55 add exception notification env via slack channel
  template/container_def.json.tpl
  variables.config.tf.example
Labels: enhancement, good first issue

#57 54 refactoring and enhancing main module
  locals.tf
  main.tf
  modules/ecs_alb/main.tf
  modules/ecs_alb/outputs.tf
  modules/ecs_alb/variables.tf
  modules/ecs_alb/versions.tf
  modules/ecs_auto_scaling/main.tf
  modules/ecs_auto_scaling/variables.tf
  modules/ecs_auto_scaling/versions.tf
  modules/ecs_fargate/main.tf
  modules/ecs_fargate/outputs.tf
  modules/ecs_fargate/variables.tf
  modules/ecs_one_off_task/main.tf
  modules/ecs_run_task/local.tf
  modules/ecs_run_task/main.tf
  modules/ecs_run_task/output.tf
  modules/ecs_run_task/variables.tf
  outputs.tf
  variables.config.tf.example
Labels: enhancement

#59 Close #58 route53 cdn cloudfront for active storage
  main.tf
  modules/route53/main.tf
  modules/route53/variables.tf
  template/container_def.json.tpl
  variables.config.tf.example
Labels: enhancement

#62 Close #60 update env for aba default email payment
  main.tf
  template/container_def.json.tpl
  variables.config.tf.example
Labels: enhancement, good first issue

#63 Close #61 explictly specify RAILS_MAX_THREADS in task
  locals.tf
  template/container_def.json.tpl
  variables.config.tf.example
Labels: enhancement, good first issue
